version: '3'
services:

  mysql:
    image: "mysql:8.0.22"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "ceiba"
      MYSQL_PASSWORD: "ceiba"
      MYSQL_DATABASE: "bicicletas_db"
