version: '3'
services:

  mysql:
    image: "mysql:5.7.10"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "ceiba"
      MYSQL_PASSWORD: "ceiba"
      MYSQL_DATABASE: "bicicletas_db"
